---
name: Time-TAI-Now
version: 0.002
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: determine current time in TAI
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::Float: 0.008
  Exporter: 0
  Math::BigRat: 0.10
  Time::UTC: 0.005
  Time::UTC::Now: 0.007
  constant: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
provides:
  Time::TAI::Now:
    file: lib/Time/TAI/Now.pm
    version: 0.002
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
